### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by markoenix** [sasjs/vscode-extension#335]
- Issue Type: `Performance`
- Extension Name: `sasjs-for-vscode`
- Extension Version: `1.16.2`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/M/AppData/Local/Temp/SASjs.sasjs-for-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by allanbowe** [comment]
Hi Marko - thanks for raising!  We'll take a look.

**Comment by allanbowe** [comment]
@markoenix - we were unable to reproduce this, and our working assumption is that the issue is related to an older version of the extension (we've made a lot of improvements since last year)

If you **are** able to reproduce, it would be great if you can also attach the text file (`cpuprofile.txt`) that you refer to in the description.

**Comment by sabhas** [comment]
via Hubstaff
User: Sabir Hassan

Project: vscode-extension - https://app.hubstaff.com/projects/2310883
Date Range: 01/26/23 - 01/26/23
Work session total: 2:23:00
Billable: Yes

Grand total: 2:23:00
