### ISSUE TITLE
EnterpriseGuide issue

### ISSUE THREAD

**Issue by srikanthbojja** [sasjs/vscode-extension#351]
Hi,

I am trying to get this extension to work with SAS enterprise guide 8.3 but unfortunately, ran into issues.

Does this extension work with SASEG?

**Comment by allanbowe** [comment]
Hi @srikanthbojja - Enterprise Guide is not a SAS runtime, simply a client for connecting to SAS.

We support the following engines in the SASjs extension:

* Viya (using client/secret)
* SAS 9 EBI (using _username / _password URL params and a "runner" Stored Process)
* SASjs Server

If you are connecting to desktop (Base) SAS using Enterprise Guide then you can use the SASjs Server option.

Otherwise you will need to set up a runner.

I'd be happy to coach you through this as it will help me to better adapt the documentation - feel free to book a call:  https://4gl.uk/book
